# Generated by Django 3.1 on 2020-08-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cell_number', models.IntegerField()),
                ('Relationship', models.CharField(choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Married', 'Married'), ('Visitor', 'Visitor')], default='Single', max_length=10)),
            ],
        ),
    ]
